default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: gdcfpd-development

test:
  <<: *default
  database: gdcfpd-test

production:
  <<: *default
  database: gdcfpd-production
